# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5ebfea6d241827fd00db2d3713eab2c757b9e9150cd7fa5bc8a1e7ff913f9982cb47004d7cb013ef0c880a65d976a59c60206fb3ce5a0be0a7a68680fdea337

test:
  secret_key_base: ef10ed086a64eb9528dfdcaef847ad0a71ac54cf4f4a3499bcc4cc61c19768252d0065a5e4bcc65584ff37ed4de3405e5ffd13a36d37bcf4acef9a47859f5386

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
